/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_dleyna_Connector */

#ifndef _Included_com_intel_dleyna_Connector
#define _Included_com_intel_dleyna_Connector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_dleyna_Connector_LOG
#define com_intel_dleyna_Connector_LOG 1L
/*
 * Class:     com_intel_dleyna_Connector
 * Method:    setJNIEnvNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_dleyna_Connector_setJNIEnvNative
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_dleyna_Connector
 * Method:    dispatchNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_dleyna_Connector_dispatchNative
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
