/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_dleyna_RendererService_Objekt */

#ifndef _Included_com_intel_dleyna_RendererService_Objekt
#define _Included_com_intel_dleyna_RendererService_Objekt
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
