/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_dleyna_ServerService */

#ifndef _Included_com_intel_dleyna_ServerService
#define _Included_com_intel_dleyna_ServerService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_dleyna_ServerService
 * Method:    dleynaMainLoopStart
 * Signature: (Lcom/intel/dleyna/Connector;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_dleyna_ServerService_dleynaMainLoopStart
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_intel_dleyna_ServerService
 * Method:    dleynaMainLoopQuit
 * Signature: (Lcom/intel/dleyna/Connector;)V
 */
JNIEXPORT void JNICALL Java_com_intel_dleyna_ServerService_dleynaMainLoopQuit
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
