/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_dleyna_GError */

#ifndef _Included_com_intel_dleyna_GError
#define _Included_com_intel_dleyna_GError
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_dleyna_GError
 * Method:    getCodeNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_dleyna_GError_getCodeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_dleyna_GError
 * Method:    getMessageNative
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_dleyna_GError_getMessageNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
