/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_dleyna_JNI */

#ifndef _Included_com_intel_dleyna_JNI
#define _Included_com_intel_dleyna_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_dleyna_JNI
 * Method:    setDirNames
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_dleyna_JNI_setDirNames
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
