/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_dleyna_RendererService */

#ifndef _Included_com_intel_dleyna_RendererService
#define _Included_com_intel_dleyna_RendererService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_dleyna_RendererService_LOG
#define com_intel_dleyna_RendererService_LOG 1L
/*
 * Class:     com_intel_dleyna_RendererService
 * Method:    dleynaMainLoopStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_dleyna_RendererService_dleynaMainLoopStart
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_dleyna_RendererService
 * Method:    dleynaMainLoopQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_dleyna_RendererService_dleynaMainLoopQuit
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_dleyna_RendererService
 * Method:    setJNIEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_dleyna_RendererService_setJNIEnv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
