/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_dleyna_RendererService */

#ifndef _Included_com_intel_dleyna_RendererService
#define _Included_com_intel_dleyna_RendererService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_intel_dleyna_RendererService_LOG
#define com_intel_dleyna_RendererService_LOG 1L
/*
 * Class:     com_intel_dleyna_RendererService
 * Method:    runNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_dleyna_RendererService_runNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
