#!/bin/sh

DOC_NAME=dleyna-lib-doc
OUT_DIR=/tmp
SDK_DIR=${SDK_DIR:-$HOME/android-sdk-linux}
API_LEVEL=${API_LEVEL:=19} # should always use the latest

rm -rf $OUT_DIR/$DOC_NAME
mkdir $OUT_DIR/$DOC_NAME
rm -f $OUT_DIR/$DOC_NAME.tgz

javadoc \
    -d $OUT_DIR/$DOC_NAME \
    -sourcepath src:gen \
    -classpath $SDK_DIR/platforms/android-$API_LEVEL/android.jar \
    -stylesheetfile apidoc.css \
    -noqualifier java.lang:java.util:android.os:android.app:android.content \
    -linkoffline http://developer.android.com/reference $SDK_DIR/docs/reference \
    src/com/intel/dleyna/lib/DLeynaException.java \
    src/com/intel/dleyna/lib/DLeynaUnknownPropertyException.java \
    src/com/intel/dleyna/lib/Icon.java \
    src/com/intel/dleyna/lib/IRendererController.java \
    src/com/intel/dleyna/lib/IRendererControllerListener.java \
    src/com/intel/dleyna/lib/IRendererDevice.java \
    src/com/intel/dleyna/lib/IRendererPushHost.java \
    src/com/intel/dleyna/lib/Renderer.java \
    src/com/intel/dleyna/lib/RendererControllerListener.java \
    src/com/intel/dleyna/lib/RendererManager.java \
    src/com/intel/dleyna/lib/RendererManagerListener.java

cd $OUT_DIR
tar czf $DOC_NAME.tgz $DOC_NAME
